source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!
xcodeproj 'OctopusKit'
workspace '../OctopusKit'
inhibit_all_warnings!


target 'OctopusKit_Example', :exclusive => true do
  pod "OctopusKit", :path => "../"
end

target 'OctopusKit_Tests', :exclusive => true do
  pod "OctopusKit", :path => "../"

  
end
