source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
project 'DemoApp'
workspace '../OctopusKit'
inhibit_all_warnings!


target 'DemoApp' do
  pod "OctopusKit", :path => "../"
end

target 'DemoAppTests' do
  pod "OctopusKit", :path => "../"

  
end
